### ISSUE TITLE
New Version 5.3.7 takes a long time in the background to open

### ISSUE THREAD

**Issue by flash25296** [cryptokatz/conceal-wallet#6]
When I upgraded to the new version I launched the installer and answered the questions and it completed install. As soon as it completed I launched the wallet and the initial splash screen came up and then disappeared from the screen and task bar for 3-4 minutes while the wallet was silently working in the background. It then finally came back up. I though the process crashed until I went into Task Manager and saw that the wallet was still active and using 30-35% CPU. You may want to add a read me file or something to let people know that this may update or migrate data in the background but that this operation may take up to 5 min and its normal. Using Win10 64 bit OS.

**Comment by krypt0x** [comment]
We did some improvements. Please try the latest version. Thanks for reporting it.
